ecomm/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from ecomm.views import (eordsummary)
app_name = 'ecomm'

urlpatterns = [
    #path('moveitem/', moveitem.MoveToPrimaryView.as_view(), name='moveitem'),
    #url(r'^picksalesorder/$', picksalesorder.SalesOrderPickingView.as_view(), name='picksalesorder'),
    ### INVENTORY OPTIONS
    #path('options/', aroptions_views.ArOptionsListView.as_view(), name='aroptions_list'),
    re_path('^ecomordsum/$', eordsummary.EcomOrdSummaryView.as_view(), name='eordsummary'),
]

mobile/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from mobile.views import (pricecheck , moveitem , picksalesorder ,
                           salesorderquery, extmovement, newgrn,additemtobatch)
app_name = 'mobile'


urlpatterns = [
    path('pricecheck/', pricecheck.PriceCheckView.as_view(), name='pricecheck'),
    path('moveitem/', moveitem.MoveToPrimaryView.as_view(), name='moveitem'),
    url(r'^picksalesorder/$', picksalesorder.SalesOrderPickingView.as_view(), name='picksalesorder'),
    url(r'^salesorderquery/$', salesorderquery.SalesOrderQueryView.as_view(), name='salesorderquery'),
    url(r'^extmovement/$', extmovement.ExtMovementView.as_view(), name='extmovement'),
    url(r'^creategrn/$', newgrn.CreateGRNView.as_view(), name='creategrn'),
    url(r'^additemtobatch/$', additemtobatch.AddItemToBatchView.as_view(), name='additemtobatch'),
]

oratech/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import include, path
from rest_framework import routers
from restapi import views as restapiviews
from rest_framework.authtoken import views as tokenviews

router = routers.DefaultRouter()
router.register(r'users', restapiviews.UserViewSet)
router.register(r'groups', restapiviews.GroupViewSet)

urlpatterns = [
    path(r'common/', include('common.urls', namespace='common'), name='common'),
    path(r'setup/', include('setup.urls', namespace='setup'), name='setup'),
    path(r'mobile/', include('mobile.urls', namespace='mobile'), name='mobile'),
    path(r'enquiry/', include('enquiry.urls', namespace='enquiry'), name='enquiry'),
    path(r'ecomm/', include('ecomm.urls', namespace='ecomm'), name='ecomm'),
    path(r'inventory/', include('inventory.urls', namespace='inventory'), name='inventory'),
    path(r'sales/', include('sales.urls', namespace='sales'), name='sales'),
    path(r'purchase/', include('purchase.urls', namespace='purcahse'), name='purchase'),
    path(r'warehouse/', include('warehouse.urls', namespace='warehouse'), name='warehouse'),
    path('accounts/login/', views.LoginView.as_view(), name='login'),
    path('accounts/logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    # path('accounts/profile/', include('common.urls',namespace='common'), name='profile'),
    path(r'admin/', admin.site.urls, name ='admin'),
    #path('restapi/', include(router.urls)),
    #path('restapi/api-auth/', include('rest_framework.urls', namespace='rest_framework'),name='restapi'),
    path(r'rest-api/', include('restapi.urls', namespace='restapi'), name='restapi'),
    path('api-token-auth/', tokenviews.obtain_auth_token, name='api-token-auth'),
    path(r'', include('common.urls', namespace='common'), name='main'),
]

mobile/views/additemtobatch.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.generic import FormView
from mobile.forms import AddToBatchForm
from inventory import (itemutil)
from common import (commonutil, querydict)

# specific to this view

REVERSE = 'mobile:additemtobatch'

@method_decorator(login_required, name='dispatch')
class AddItemToBatchView(FormView):
    template_name = 'mobile/additemtobatch.html'
    form_class = AddToBatchForm
    context_object_name = 'form'
    rows = None
    MYCONTEXT = {}
    success_url = "/mobile/additemtobatch/"
    batchid  = 1

    def get(self, request, *args, **kwargs):
        return super(AddItemToBatchView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        pass

    def get_initial(self):
        initial =  {'item_number': "",
                    }
        print('inital:', initial)
        return initial

    def get_form_kwargs(self):
        kwargs = super(AddItemToBatchView, self).get_form_kwargs()
        kwargs['hiddenfields'] = []
        if commonutil.hasstrvalue(self.request.POST.get('batch_name')):
            kwargs['hiddenfields'] =  ['batch_name']
        return kwargs

    def get_queryset(self):
        pass

    def get_success_url(self):
        return reverse(REVERSE)

    def get_context_data(self, **kwargs):
        context = super(AddItemToBatchView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        userid = self.request.user.user_id
        businessunit = self.request.user.bu_id
        context['businessunit'] = businessunit
        commonutil.debugmessage('In context','Get batch lines')
        print(self.batchid)
        sql = """ Select Item_Id, Item_Number, Item_Name , Batch_ID
                From Inv_Item_BATCH_LINES_VA
                Where Batch_ID = {}""".format((self.batchid))
        # self.rows = dbfuncs.exec_sql(sql)
        self.rows , self.tableheader, self.tablecolumns = querydict.get_rowset(querydict.Q_GETBATCHITEMS,[self.batchid])
        print(self.batchid, self.rows)
        context['MYCONTEXT'] = self.MYCONTEXT
        context['rows'] = self.rows
        context['rows_tableheader'] = self.tableheader
        context['rows_tablecolumns'] = self.tablecolumns
        return context

    def form_valid(self, form, **kwargs):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        # perform a action here
        context = self.get_context_data(**kwargs)
        userid = self.request.user.user_id
        itemnumber = form.cleaned_data['item_number']
        batchname = form.cleaned_data['batch_name']
        self.batchid , message = itemutil.add_itemtobatch(p_batchname=batchname, p_itemnumber=itemnumber,p_userid=userid)
        commonutil.debugmessage(self.batchid,'2a')
        if not commonutil.hasintnonaerovalue(self.batchid):
            self.MYCONTEXT['errormessage'] = message
            self.form_invalid(form)
        else:
            self.MYCONTEXT['successmessage'] = message
        return super().form_invalid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

mobile/views/extmovement.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import FormView
from mobile.forms import ExtMovementForm
from inventory import locationutil as locationutil
from common import (sessionfunc, commonutil, dbfuncs)

# specific to this view


REVERSE = 'mobile:extmovement'

@method_decorator(login_required, name='dispatch')
class ExtMovementView(FormView):
    template_name = 'mobile/extmoveitem.html'
    form_class = ExtMovementForm
    context_object_name = 'form'
    itemdict = {}
    success_url = "/mobile/extmovement/"


    def get(self, request, *args, **kwargs):
        return super(ExtMovementView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        return self.form_invalid(form, **kwargs)

    def get_initial(self):
        tosublocation =  dbfuncs.get_primarysubloc('PRIMARY GRN', self.request.user.location_id)
        print('initial')
        return {'to_sub_location': tosublocation}

    def get_form_kwargs(self):
        kwargs = super(ExtMovementView, self).get_form_kwargs()
        kwargs['hiddenfields'] =  ['to_sub_location']
        print('1', kwargs)
        return kwargs

    def get_queryset(self):
        pass

    def get_success_url(self):
        return reverse(REVERSE)

    def form_invalid(self, form, **kwargs):
        context = self.get_context_data(**kwargs)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        locationid = sessionfunc.getset_sessionval(self.request, 'locationid', None,self.request.user.location_id)
        page = self.request.POST.get('page')
        userid = self.request.user.user_id
        # self.form_class['to_sub_location'].   to_sub_location(initial='GRN STAGING')
        context = super(ExtMovementView , self).get_context_data(**kwargs)
        items = None
        item = None
        businessunit = self.request.user.bu_id
        context['businessunit'] = businessunit
        userid = self.request.user.user_id
        movementtype =  self.request.POST.get('movementtype')
        itemnumber =  self.request.POST.get('item_number')
        fromsublocation =  self.request.POST.get('from_sub_location')
        quantity =  self.request.POST.get('quantity')
        tosublocation =  self.request.POST.get('to_sub_location')
        fromlocationid = sessionfunc.get_location_id(self.request)
        tolocationid = sessionfunc.get_location_id(self.request)
        if commonutil.hasstrvalue(itemnumber):
            if not commonutil.hasstrvalue(tosublocation):
                tosublocation = dbfuncs.get_primarysubloc('PRIMARY GRN', tolocationid)
            message = locationutil.move_item(movementtype,userid, itemnumber,
                                            fromlocationid, fromsublocation,
                                            int(quantity), tolocationid, tosublocation)
            if message == 'OK':
                self.itemdict['successmessage'] = 'Item {0} moved from {1} to {2} successfully {3}'.format(
                    itemnumber, fromsublocation, tosublocation, quantity )
            else:
                self.itemdict['errormessage'] = message
        context['itemdict'] = self.itemdict
        return context

mobile/views/moveitem.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import FormView
from mobile.forms import MoveItemToPrimayForm
from inventory import locationutil as locationutil


# specific to this view


@method_decorator(login_required, name='dispatch')
class MoveToPrimaryView(FormView):
    template_name = 'mobile/moveitem.html'
    form_class = MoveItemToPrimayForm
    context_object_name = 'form'
    initial_dict = {
        "title": "My New Title",
        "description": " A New Description",
        "available": True,
        "email": "abc@gmail.com"
    }
    itemdict = {}
    success_url = "/mobile/moveitem/"

    def get(self, request, *args, **kwargs):
        return super(MoveToPrimaryView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        pass

    def get_context_data(self, **kwargs):
        context = super(MoveToPrimaryView, self).get_context_data(**kwargs)
        page = self.request.GET.get('page')
        userid = self.request.user.user_id
        items = None
        item = None
        businessunit = self.request.user.bu_id
        context['businessunit'] = businessunit
        context['itemdict'] = self.itemdict
        context['rows'] = items
        context['item'] = item
        return context

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        # perform a action here
        context = self.get_context_data(**kwargs)
        userid = self.request.user.user_id
        movementtype = 'INTERNALTOINTERNAL'
        itemnumber = form.cleaned_data['item_number']
        fromsublocation = form.cleaned_data['from_sub_location']
        quantity = form.cleaned_data['quantity']
        tosublocation = form.cleaned_data['to_sub_location']
        fromlocationid = sessionfunc.get_location_id(self.request)
        tolocationid = sessionfunc.get_location_id(self.request)
        message = locationutil.move_item(movementtype,userid, itemnumber,
                                        fromlocationid, fromsublocation,
                                        quantity, tolocationid, tosublocation)
        if message == 'OK':
            self.itemdict['successmessage'] = 'Item {0} moved from {1} to {2} successfully {3}'.format(
                itemnumber, fromsublocation, tosublocation, quantity )
        else:
            self.itemdict['errormessage'] = message
            self.form_invalid(form)
        context['itemdict'] = self.itemdict
        return super().form_valid(form)

    def form_invalid(self, form):
        return super().form_invalid(form)

mobile/views/salesorderquery.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import FormView
from mobile.forms import SalesOrderQueryForm
from common import dbfuncs as dbfunc
from common.models import (ArSalesorderHeaders)

# specific to this view

REVERSE='mobile:salesorderquery'

@method_decorator(login_required, name='dispatch')
class SalesOrderQueryView(FormView):
        template_name = 'mobile/salesorderquery.html'
        context_object_name = 'form'
        form_class = SalesOrderQueryForm
        itemdict = {}
        MYCONTEXT = {}

        def get(self, request, *args, **kwargs):
            self.MYCONTEXT['order_number'] = None
            return super(SalesOrderQueryView, self).get(request, *args, **kwargs)

        def post(self, request, *args, **kwargs):
            form = self.get_form()
            return self.form_invalid(form, **kwargs)

        def get_queryset(self):
            pass

        def get_success_url(self):
            return reverse(REVERSE)

        def form_invalid(self, form, **kwargs):
            context = self.get_context_data(**kwargs)
            return self.render_to_response(context)

        def get_context_data(self, **kwargs):
            context = super(SalesOrderQueryView, self).get_context_data(**kwargs)

            f_ordernumber = self.request.POST.get('order_number')
            f_orderstatus = str(self.request.POST.get('order_status'))+'%'
            f_linestatus = str(self.request.POST.get('Line_status'))+'%'
            f_linephase = str(self.request.POST.get('Line_phase'))+'%'
            f_deliverystatus =  str(self.request.POST.get('delivery_status'))+'%'
            f_webordernumber = str(self.request.POST.get('web_order_number'))+'%'
            orderid = None
            if f_ordernumber != "":
                orderid = dbfunc.select_sqlfunc("SalOrder_Pkg.Get_OrderIdFromNumber('{0}')".format(f_ordernumber))
                print(orderid)
                orderheader = ArSalesorderHeaders.objects.filter(order_header_id=orderid)
                context['rows'] = orderheader
                if orderheader:
                    orderh = orderheader[0]
                    sql = """Select Order_Header_Id,
                                    Qty_Ordered_Units,
                                    Qty_Accepted_Units,
                                    Qty_Userpicked_Units,
                                    Qty_Delivered_Units,
                                    Qty_Invoiced_Units,
                                    Qty_Cancelled_Units
                                    From AR_SALORDLINESTAT_V
                            Where Order_Header_ID = {0}""".format(orderh.order_header_id)
                    qtystatus = dbfunc.exec_sql(sql,'dict')
                    context['rowset2'] = qtystatus
                    sql = """Select
                                Total_Lines , 
                                New_Count,
                                Approved_Count,
                                Picked_Count,
                                Invoiced_Count,
                                Delivered_Count,
                                Readytopick_Count,
                                Readytodeliver_Count,
                                Weorder_Count
                                    From AR_SALORDLINESTAT_V
                            Where Order_Header_ID = {0}""".format(orderh.order_header_id)
                    linestatus = dbfunc.exec_sql(sql,'dict')
                    context['rowset3'] = linestatus
                    sql = """Select Sl_No,Item_Number,Qty_Ordered_Units,
                                Qty_Picked_Units,Qty_UserPicked_Units,
                          Qty_Delivered_Units,LineStatus,LinePhaseCode,
                          t_OrderNumber,Delivery_status,Delivery_Date,Item_name
                            From REP_ITEMSALESORDER_V
                         Where Order_Header_ID = {0}
                        And  LineStatus like '{1}'
                        And  LinePhaseCode like '{2}'
                        And  nvl(T_ORDERNUMBER,'%') like '{3}'
                        And  nvl(Delivery_Status,'%') like '{4}'
                        order by 1,2,3""".format(orderh.order_header_id, f_linestatus,
                                f_linephase, f_webordernumber,f_deliverystatus)
                    lines = dbfunc.exec_sql(sql,'dict')
                    context['rowset4'] = lines
            page = self.request.POST.get('page')
            userid = self.request.user.user_id
            return context

mobile/templates/mobile/additemtobatch.html
{% extends 'common/generic_list_post.html' %}
{% block moduletitle %}
    Add Item to Batch
{% endblock %}
{% block findaction %} {% endblock %}
{% block getpost %}post{% endblock %}
{% block findform %}
    {{ form }}
     <input type="submit" class="btn btn-info" value="Submit">
{% endblock %}
Items in Batch
{% block rowaction %}
{% endblock %}
    {% block postlist %}
  {% endblock %}

        <div> <h3> {% block table2title %}Quantity Summary {% endblock  %}  </h3> </div>
        {% block tableheader2 %}
        {% endblock %}
    {% block tablerow2 %}
        {% endblock %}
{% block table3title %} Line Summary  {% endblock  %}
        {% block tableheader3 %}
        {% endblock %}
       {% block tablerow3 %}

        {% endblock %}
{% block table4title %} Lines  {% endblock  %}
        {% block tableheader4%}
        {% endblock %}
       {% block tablerow4 %}
        {% endblock %}
{% block createaction %}

{% endblock %}

mobile/templates/mobile/extmoveitem.html
{% extends 'common/nonmodel_form.html' %}
{% block moduletitle %}
    External to Internal Movement
    <br>

{% endblock %}
    {% block errormessage %}
    {{ itemdict.errormessage }}
    {% endblock %}

    {% block successmessage %}
    {{ itemdict.successmessage }}
    {% endblock %}
{% block createaction %}

{% endblock %}

mobile/templates/mobile/moveitem.html
{% extends 'common/nonmodel_form.html' %}
{% block moduletitle %}
    Move Item to Primary or Any Sub Location
    <br>

{% endblock %}
    {% block errormessage %}
    {{ itemdict.errormessage }}
    {% endblock %}

    {% block successmessage %}
    {{ itemdict.successmessage }}
    {% endblock %}
{% block createaction %}

{% endblock %}

mobile/templates/mobile/newgrn.html
{% extends 'common/generic_list_post.html' %}
{% block moduletitle %}
    Add / Ammend GRN

{% endblock %}
{% block findaction %}{% url 'mobile:creategrn' %} {% endblock %}
{% block getpost %}{% if MYCNTEXT.grnnumber or MYCONTEXT.itemnumber %}post{% else %}post{% endif %}{% endblock %}

{% block formattr %}document.myform.itemn_number.focus(){% endblock %}
{% block findform %}
    {% if myform %}
       {{ myform | safe }}
    {% else %}
        {{ form }}
    {% endif %}
     <input type="submit" class="btn btn-info" value="Submit">
    {% if not MYCONTEXT.grnnumber %}
     <input type="submit" class="btn btn-info" value="Goods in from PO">
    {% endif %}
{% endblock %}
{% block tableheader %}
<th>ID</th>
<th>GRN#</th>
<th>Location</th>
<th>Delivery Note</th>
<th>Supplier# </th>
<th>SupplierName</th>
<th>Status</th>
<th>Date</th>
 {% endblock %}
{% block tablerow %}
      <td>{{ row.GRN_ID  }}</td>
      <td>{{ row.GRN_NUMBER  }}</td>
      <td>{{ row.LOCATION_NAME  }}</td>
      <td>{{ row.DELIVERY_NOTE_REF  }}</td>
        <td>{{ row.SUPPLIER_NUMBER  }}</td>
         <td>{{ row.SUPPLIER_NAME  }}</td>
       <td>{{ row.GRN_STATUS  }} </td>
        <td>{{ row.LAST_UPDATE_DATE  }}</td>
    {% comment %}
        <a href="{%  url 'mobile:salesorderquery' %} {{row.order_header_id }} "><span class="glyphicon glyphicon-pencil" >{{row.order_header_id }}</span></a>
             </td>
             {% endcomment %}
{% endblock %}
{% block rowaction %}
{% endblock %}
    {% block postlist %}

        <div class="d-flex justify-content-center">
            <p><h3><a href="{%  url 'mobile:creategrn' %}" > Start New Goods In </a> </h3></p>
         </div>
  {% endblock %}

        <div> <h3> {% block table2title %}Goods In Lines {% endblock  %}  </h3> </div>
        {% block tableheader2 %}
                <th> Item Number </th>
                 <th> BIN </th>
                <th>Sub Location</th>
                 <th> Item Name </th>
                 <th> Qty Received </th>
        {% endblock %}
    {% block tablerow2 %}
            <td>{{row2.ITEM_NUMBER }}</td>
            <td>{{row2.SUBIN }}</td>
            <td>{{row2.SUB_LOCATION }}</td>
            <td>{{row2.ITEM_NAME }}</td>
            <td>{{row2.QTY_RECEIVED_UNITS }}</td>
        {% endblock %}
{% block table3title %} Approved Purchase Orders  {% endblock  %}
        {% block tableheader3 %}
                <th>PO ID</th>
                <th>PO Number</th>
                <th>status</th>
                <th>Supplier Number</th>
                <th>Supplier Name</th>
                <th>Status Date</th>
                <th>Supplier Id</th>
        {% endblock %}
       {% block tablerow3 %}
      <td>{{ row.PO_HEADER_ID }}</td>
      <td>{{ row.PO_NUMBER  }}</td>
       <td>{{ row.ORDER_STATUS  }} </td>
        <td>{{ row.SUPPLIER_NUMBER  }}</td>
         <td>{{ row.SUPPLIER_NAME  }}</td>
        <td>{{ row.ORDER_STATUS_DATE  }}</td>
      <td>{{ row.SUPPLIER_ID }}</td>
        {% endblock %}
{% block table4title %} Lines  {% endblock  %}
        {% block tableheader4%}
                <th>Sl No</th>
                <th>Item Number</th>
                <th>Ordered</th>
                <th>Accepted</th>
                <th>Picked</th>
                <th>Delivered</th>
                <th>Status</th>
                <th>Phase</th>
                <th>Web Order#</th>
                <th>Delivery Status</th>
                <th>Delivered On</th>
                <th>Item Name</th>
        {% endblock %}
       {% block tablerow4 %}
            <td>{{row4.SL_NO }}</td>
            <td>{{row4.ITEM_NUMBER  }}</td>
            <td>{{row4.QTY_ORDERED_UNITS  }}</td>
            <td>{{row4.QTY_PICKED_UNITS }}</td>
            <td>{{row4.QTY_USERPICKED_UNITS  }}</td>
            <td>{{row4.QTY_DELIVERED_UNITS  }}</td>
            <td>{{row4.LINESTATUS }}</td>
             <td>{{row4.LINEPHASECODE }}</td>
            <td>{{row4.T_ORDERNUMBER }}</td>
            <td>{{row4.DELIVERY_STATUS }}</td>
            <td>{{row4.DELIVERY_DATE  }}</td>
            <td>{{row4.ITEM_NAME  }}</td>
        {% endblock %}
{% block createaction %}
{% endblock %}
{% block scripts %}
    <script>
     $(function () {
         $('input[type="text"], textarea').val('');
        $('select').each(function() {
        $(this).val($(this).find('option').val());
            };
  });

</script>
{% endblock %}

mobile/templates/mobile/picksalesorder.html
{% extends 'common/menu.html' %}
{% block title %} Sales Order Picking  {% endblock %}
{% block content_block %}
    <h3> Sales Order Picking </h3>
    {% block prelist %}
        {% endblock %}
{% if MYCONTEXT.errormessage %}
    <p class="p-3 mb-2 text-danger  font-weight-bolder ">
     {{  MYCONTEXT.errormessage }}
    </p>
{% endif %}
{% if MYCONTEXT.successmessage %}
    <p class="p-3 mb-2 bg-primary text-white font-weight-bolder ">
    {{  MYCONTEXT.successmessage }}
    </p>
{% endif %}
<form action="{% url 'mobile:picksalesorder' %}" method="post">
    {% csrf_token %}
<div class="container">

                  {% if not MYCONTEXT.mode or MYCONTEXT.mode == "ADD" %}
                          <div class="row">
                      <div class="col-sm-2 pull-right " >  <label for="order_number">Order Number</label>  </div>
                  <div class="col-md-6 pull-left " >  <input id="order_number" type="text" name="order_number" value="">  </div>
                          </div>
              {%  else %}
                    <input id="order_number" type="hidden"   name="order_number" value="{{ MYCONTEXT.order_number }}">
                  {% if MYCONTEXT.enablepalleting == "Y" %}
                  <div class="row">
                      <div class="col-sm-2 pull-right " >  <label for="box_slno">Pallet Reference</label>  </div>
                      <div class="col-md-6 pull-left " >  <input id="box_slno" type="text" name="box_slno" value="{{ MYCONTEXT.boxslno }}">  </div>
                  </div>
                      {% endif %}
                  {% if MYCONTEXT.pickingconfirmation == "THREEWAY" %}
                      <div class="row">
                      <div class="col-sm-2 pull-right ">  <label for="line_id">Scan Pick Barcode </label>  </div>
                      <div class="col-md-6 pull-left " >  <input id="line_id" type="text" name="line_id" value="">  </div>
                      </div>
                      {% else %}
                      <INPUT TYPE="hidden" NAME="line_id" id="line_id" VALUE="">
                      {% endif %}
                  <div class="row">
                     <div class="col-sm-2 pull-right">  <label for="from_sub_location"> From Sub Location </label>  </div>
                    <div class="col-md-6 pull-left">  <input id="from_sub_location" type="text" name="from_sub_location" value="">  </div>
                  </div>
                    {% if MYCONTEXT.pickingconfirmation == "TWOWAY" %}
                        {% comment %} no action {% endcomment %}

                        {% else %}
                  <div class="row">
                     <div class="col-sm-2 pull-right " >  <label for="picked_item_number">Scan Item you picked </label> </div>
                    <div class="col-md-6 pull-left " >  <input id="picked_item_number" type="text" name="picked_item_number" value="">  </div>
                  </div>
                        <div class="row">
                     <div class="col-sm-2 pull-right " >  <label for="quantity">Quantity</label>   </div>
                    <div class="col-md-6 pull-left " >  <input id="quantity" type="text" name="quantity" value="">  </div>

                  </div>
                  </div>
                        {% endif %}
             {% endif %}
    <div class="row">
    <div class="col-sm-2 pull-right " > </div>
    <div class="col-sm-2 pull-right " > </div>
    <div class="col-md-6 pull-right " >  <input type="submit" class="btn btn-info" value="Submit"> </div>
</div>
<input id="order_id" type="hidden"   name="order_id" value="{{ MYCONTEXT.order_id }}">
<input id="categorystring" type="hidden"   name="categorystring" value="{{ MYCONTEXT.categorystring }}">
<input id="pickingconfirmation" type="hidden"   name="pickingconfirmation" value="{{ MYCONTEXT.pickingconfirmation }}">
<input id="enable_palleting" type="hidden"   name="enable_palleting" value="{{ MYCONTEXT.enablepalleting }}">
</form>
</form>
   {%  if linestopick %}
                <div class="d-flex">
                        <table class="table table-striped table-bordered table-sm" >
                            <thead class="bg-info">
                            <tr>
                     {% block tableheader %}
        <th>Order#</th>
            <th>Line ID</th>
            <th>Sub Location</th>
            <th>Item Number</th>
            <th>Item Name</th>
            <th>Loc Stock</th>
            <th>SubLoc Stock</th>
            <th>Ordered</th>
            <th>Picked</th>
            <th>To Pick</th>
            <th>To Pick (c)</th>
                     {% endblock %}

                    </tr>
                  </thead>
                  <tbody>
                    {{  linestopick | safe }}
                  {%   for row in rows %}
                   <tr>
                       {% block rowaction  %}
                   {% endblock %}
                      {% block tablerow %}
                       {% endblock %}


                    </tr>
                  {%   endfor %}
                  </tbody>
                </table>
           </div>
    {% endif %}
{% endblock %}